export const ADD_BASKET = 'ADD_BASKET';
export const REMOVE_BASKET = 'REMOVE_BASKET';
export const ADD_BASKET_SUCCESS = 'ADD_BASKET_SUCCESS';
export const ADD_BASKET_FAIL = 'ADD_BASKET_FAIL';
export const FETCH_BASKET = 'FETCH_BASKET';
export const FETCH_BASKET_INIT = 'FETCH_BASKET_INIT';
export const FETCH_BASKET_SUCCESS = 'FETCH_BASKET_SUCCESS';
export const FETCH_BASKET_FAIL = 'FETCH_BASKET_FAIL';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
